#!/bin/bash
#
# How to Install Under Linux
#

# 1: Install Compilation Tools
sudo apt-get install libopenmpi-dev gfortran build-essential cmake git
# 2: Compile it under $HOME Directory
cd $HOME
mkdir TestCFL3D
cd TestCFL3D
got clone git@github.com:gitlarky/CFL3D.git
cd CFL3D/external
./build_cgns
cd ../build
cmake ../
make -j 8
# 3: Move compiled file into /opt and set environment
cd ..
echo "# Add CFL3D executables to PATH">>$HOME/.bashrc
echo "alias testcfl3d=export PATH=$PWD/build/bin:\$PATH">>$HOME/.bashrc